package com.yu.mboocode.agent.tool.network;

import com.yu.mboocode.agent.tool.ToolErrorCode;

public enum NetworkToolErrorCode implements ToolErrorCode {
    INVALID_ARGUMENT,
    NETWORK_INVALID_URL,
    NETWORK_PRIVATE_ACCESS_DISABLED,
    NETWORK_TARGET_DENIED,
    NETWORK_MIXED_ADDRESS_DENIED,
    NETWORK_DNS_RESOLUTION_FAILED,
    NETWORK_TARGET_CHANGED,
    NETWORK_REDIRECT_REQUIRES_DIRECT_FETCH,
    NETWORK_REDIRECT_LIMIT_EXCEEDED,
    NETWORK_HTTPS_DOWNGRADE_DENIED,
    NETWORK_TIMEOUT,
    NETWORK_CANCELLED,
    NETWORK_RATE_LIMITED,
    NETWORK_HTTP_ERROR,
    NETWORK_RESPONSE_TOO_LARGE,
    NETWORK_UNSUPPORTED_CONTENT_TYPE,
    NETWORK_DECODE_ERROR,
    NETWORK_REQUEST_FAILED,
    WEB_SEARCH_PROVIDER_ERROR,
    WEB_SEARCH_INVALID_RESPONSE;

    @Override
    public String getCode() {
        return name();
    }
}
