spring:
  application:
    name: mboo-code
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.home}/.mboo/mboo_data.sqlite
  sql:
    init:
      mode: always
      schema-locations: classpath:db/sqlite/schema.sql
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful

mboo:
  version: ${MBOO_VERSION:0.0.1-SNAPSHOT}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc.html
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.yu.mboocode
