package com.yu.mboocode.llm.tool.file;

public enum FileToolErrorCode {
    INVALID_ARGUMENT,
    INVALID_PATH,
    PATH_NOT_FOUND,
    PATH_NOT_DIRECTORY,
    PATH_NOT_REGULAR_FILE,
    PATH_IGNORED,
    GIT_INTERNAL_WRITE_DENIED,
    FILE_TOO_LARGE,
    BINARY_FILE,
    UNSUPPORTED_ENCODING,
    INVALID_GLOB,
    INVALID_REGEX,
    RG_NOT_FOUND,
    DEPENDENCY_VERSION_UNSUPPORTED,
    RG_TIMEOUT,
    RG_EXECUTION_FAILED,
    EDIT_TEXT_NOT_FOUND,
    EDIT_TEXT_NOT_UNIQUE,
    FILE_CHANGED,
    ATOMIC_REPLACE_UNSUPPORTED,
    FILE_READ_FAILED,
    FILE_WRITE_FAILED,
    FILE_TOOL_ERROR
}
